### ISSUE TITLE
intlify/vue-i18n/no-unused-keys does not work with TS/TSX

### ISSUE THREAD

**Issue by 8bu** [intlify/eslint-plugin-vue-i18n#103]
I have tried to integrate this rule for an hour but can't make this work for my project. I'm using Vue with Typescript and my Component are all .tsx
Other rule were working just fine but this rule didn't work as my expected. Here are my rule config & setting, I'm using `plugin:@intlify/vue-i18n/recommended` btw:
```
'@intlify/vue-i18n/no-unused-keys': ["error", {
      "src": "./src",
      "extensions": [".tsx", ".ts"],
      "enableFix": true,
    }],
```
```
  settings: {
    'vue-i18n': {
      localeDir: './src/locales/*.{json,json5,yaml,yml}',
    }
  }

```

**Comment by ota-meshi** [comment]
Thank you for this issue!

Could you try adding the following configuration?

```js
  overrides: [
    {
      files: ['*.json', '*.json5'],
      extends: ['plugin:@intlify/vue-i18n/base'],
    },
    {
      files: ['*.yaml', '*.yml'],
      extends: ['plugin:@intlify/vue-i18n/base'],
    }
  ]
```

This plugin uses a special parser for yaml and json, but it's probably the TypeScript parser you have configured is used.
If the above configuration works, we need to add a workaround to the FAQ.

**Comment by 8bu** [comment]
> 
> 
> Thank you for this issue!
> 
> Could you try adding the following configuration?
> 
> ```js
>   overrides: [
>     {
>       files: ['*.json', '*.json5'],
>       extends: ['plugin:@intlify/vue-i18n/base'],
>     },
>     {
>       files: ['*.yaml', '*.yml'],
>       extends: ['plugin:@intlify/vue-i18n/base'],
>     }
>   ]
> ```
> 
> This plugin uses a special parser for yaml and json, but it's probably the TypeScript parser you have configured is used.
> If the above configuration works, we need to add a workaround to the FAQ.

Unfortunately, I tried but it didn't work.
Here is my .eslintrc.js content: https://ghostbin.co/paste/yubfk
I will setup codesandbox reproduce this issue soon.

**Comment by ota-meshi** [comment]
I was able to use your configuration file to get it working. Can you share a minimal repository to reproduce this issue?

**Comment by 8bu** [comment]
I will try to arrange time to create a reproduce repo & codesandbox tonight (UTC+8). Thank u

**Comment by ota-meshi** [comment]
If you still have similar issues,  please open a new issue.
