### ISSUE TITLE
[no-missing-keys] option for default locale

### ISSUE THREAD

**Issue by alexcroox** [intlify/eslint-plugin-vue-i18n#146]
**What rule do you want to change?**
no-missing-keys

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option to specify the default locale file

**Additional context**
Often, and especially during development, I will setup all my keys for en-GB.json but other locales will only have a few or a lot of gaps until they are completed (this is done via an external programme that automates the creation of the missing keys). With the behaviour of vue-i18n being that it falls back to the default locale if a key is missing.

It would be great if we could specify a single file to check instead of it looking in all locales for missing keys.

**Comment by ota-meshi** [comment]
Thank you for this issue!

I think we need to add a rule and separate goals.
The `no-missing-keys` rule changes it to not report if it exists in one of the locales.
I think we need to add a rule that reports a key that exists in one locale and is missing in another. It rule we add must provide an option to allow the user to specify a locale to ignore even if the key does not exist.

**Comment by alexcroox** [comment]
Yes I think you are right, my goal is to check if my Vue templates reference a key that isn't in a locale json file, whereas no-missing-keys compares locale against locale without any concern for Vue templates.

**Comment by alexcroox** [comment]
Amazing thank you!!
