### ISSUE TITLE
How to deal with internationalized copywriting in the following situations

### ISSUE THREAD

**Issue by leotian** [intlify/eslint-plugin-vue-i18n#178]
![image](https://user-images.githubusercontent.com/10192886/112826319-686c1880-90bf-11eb-9b23-aefc6156fc66.png)

![image](https://user-images.githubusercontent.com/10192886/112826433-8e91b880-90bf-11eb-8f61-886ee256e9ac.png)

**Comment by ota-meshi** [comment]
I close this issue because I don't understand what you are saying.

**Comment by leotian** [comment]
I mean，variables in data() {} or variables in computed。Can't check it out now。
