### ISSUE TITLE
How to deal with the internationalization of variables in data() {} or variables in computed？

### ISSUE THREAD

**Issue by leotian** [intlify/eslint-plugin-vue-i18n#180]
How to deal with internationalized copywriting in the following situations？ 
![image](https://user-images.githubusercontent.com/10192886/114177749-59168600-996f-11eb-94df-dfcbc8037926.png)

![image](https://user-images.githubusercontent.com/10192886/114177767-5c117680-996f-11eb-9999-f662fa6252c2.png)

**Comment by ota-meshi** [comment]
I don't know what your problem is. Please open the issue using the issue template.
