### ISSUE TITLE
`recommended` config does not match docs

### ISSUE THREAD

**Issue by FloEdelmann** [intlify/eslint-plugin-vue-i18n#275]
According to the docs, these rules should be enabled when extending `plugin:@intlify/vue-i18n/recommended` in my ESLint config:

![grafik](https://user-images.githubusercontent.com/202916/145185588-a220ff26-31a3-4bc7-83ab-3fc3bbe54c92.png)

However, the `recommended` config file only contains these four rules:

https://github.com/intlify/eslint-plugin-vue-i18n/blob/8e5b62b81f9c4591e16c023ebc6ccaf11b3e458e/lib/configs/recommended.ts#L15-L20

The `base` config (which the `recommended` config extends) does not configure any rules, apart from turning off some core ESLint rules in YAML files for YAML compatibility.

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
Rules that are not currently turned ON depend on the version of vue-i18n users using, and cannot be included in the currently provided configuration.
I think it is better to provide new recommended configuration for each vue-i18n version different from it.
