### ISSUE TITLE
Cannot disable rule

### ISSUE THREAD

**Issue by Doogiemuc** [intlify/eslint-plugin-vue-i18n#279]
**Tell us about your environment**

- **ESLint version:** 6.2.0
- **eslint-plugin-vue version:** 7.0.0
- **vue-i18n version:** 9.2.0-beta.25 
- **Node version:** 16.13.1
- **Vue version:** VUE 3

**Please show your full configuration:**

`.eslintrc`
```json5
module.exports = {
  root: true,
  env: {
    node: true
  },
  'extends': [
    'plugin:vue/vue3-essential',
    'eslint:recommended'
  ],
  parserOptions: {
    parser: 'babel-eslint'
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
		'@intlify/vue-i18n/no-v-html': 'off',    // allow HTML in translations   <== STILL SHOWS WARNING ???
  },
  overrides: [
    {
      files: [
        '**/__tests__/*.{j,t}s?(x)',
        '**/tests/unit/**/*.spec.{j,t}s?(x)'
      ],
      env: {
        mocha: true
      },
    }
  ]
}
```

**What did you do?**
I want to use HTML in my translations. Ok there is warning for that. I would like to disable this warning.

**What did you expect to happen?**
Use my translations. Insert the raw HTML from the translation texts into my page

**What actually happened?**
A warning is shown in the browser console, despite the rule beeing disabled in .eslintrc
"[intlify] Detected HTML in ... "

**Comment by Doogiemuc** [comment]
This also didn't help: https://stackoverflow.com/questions/69795845/vue-3-eslint-warning-intlify-detected-html

**Comment by ota-meshi** [comment]
I'm not sure what your problem is.  Could you provide a repository that can reproduce your problem and steps to reproduce it?

**Comment by Doogiemuc** [comment]
Here is my repo. It's a large mobile application (PWA, web based): https://github.com/Doogiemuc/liquido-mobile-pwa-vue3

My problem is actually simple:  The project is running fine. But I see a lot of warnings in the browser console:

````
[intlify] Detected HTML in 'Hallo <b>{nickname}</b> ! '
````

I know what these warnings mean. (I know what an XSS-attach is.) My HTML strings are fine. They are static. I want, and need to(!!!) use HTML in my vue-i18n translations.  

=> I simply want to get rid of the warning.

**Comment by ota-meshi** [comment]
Thank you for providing the repository.

You need to report the issue on https://github.com/intlify/vue-i18n-next as the issue has nothing to do with the eslint plugin.
Please report new issues according to the issue template of `vue-i18n-next`.

I close this issue because I can't do anything with this repository.
