### ISSUE TITLE
Include translation strings in backticks

### ISSUE THREAD

**Issue by darthf1** [intlify/eslint-plugin-vue-i18n#301]
Hi!

For reasons currently unknown to me, I have translation strings, without variables, in backticks:
```js
$t(`my.translation_key`)
```

These strings are not analyzed by this plugin. As soon as I change the code to:
```js
$t('my.translation_key')
```

I get errors telling me `my.translation_key` does not exist in localization message resources.

Ill go try and convert all backticks to a normal single quote, but in the meantime, is it possbile to analyse these strings in backticks as well?

**Comment by ota-meshi** [comment]
It seems like a bug that the `@intlify/vue-i18n/no-missing-keys` rule doesn't check template literals.

**Comment by darthf1** [comment]
Great! Thanks for following up.

I'm not sure it's only those two rules, I thought it was `@intlify/vue-i18n/key-format-style` as well, but I have to check.

**Comment by darthf1** [comment]
So I have the following in my config:
```js
{
    rules: {
        '@intlify/vue-i18n/key-format-style': [
          'error',
          'snake_case',
          { splitByDots: true },
        ],
    }
}
```

If I put the following in my code:
```js
$t(`notSnakeCase`)
```

It is also not analyzed

**Comment by ota-meshi** [comment]
The key-format-style rule checks JSON and YAML.
