### ISSUE TITLE
@intlify/vue-i18n/no-unused-keys in Typescript

### ISSUE THREAD

**Issue by maggie0002** [intlify/eslint-plugin-vue-i18n#309]
**Please show your full configuration:**
https://github.com/maggie0002/balena-device-ui/blob/main/ui/.eslintrc.js

**What did you do?**
I can't seem to get `@intlify/vue-i18n/no-unused-keys` to work in a Quasar Typescript project. I have tried all the various suggestions in the docs and issues:

1. Added .json to my lint command: `"lint": "eslint --ext .js,.ts,.vue,.json ./",`
2. Included an override:

```
  overrides: [
    {
      files: ['*.json', '*.json5'],
      extends: ['plugin:@intlify/vue-i18n/base'],
    },
    {
      files: ['*.yaml', '*.yml'],
      extends: ['plugin:@intlify/vue-i18n/base'],
    }
  ]
```

Still no luck. Other linting rules seem to work fine.

**What did you expect to happen?**

Expecting the following key to be marked as unused: `  "Response": "Response",`

**Comment by ota-meshi** [comment]
The `'plugin:@typescript-eslint/recommended-requiring-type-checking'` ruleset cannot be applied to `json` and `yaml`, so linting seems to fail.

You probably need to change the configuration as follows:

```diff
    // https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#usage
    // ESLint typescript rules
    'plugin:@typescript-eslint/recommended',
-    'plugin:@typescript-eslint/recommended-requiring-type-checking',

// ...

  },

+  overrides: [
+    {
+      files: ['*.json', '*.json5'],
+      extends: ['plugin:@intlify/vue-i18n/base']
+    },
+    {
+      files: ['*.yaml', '*.yml'],
+      extends: ['plugin:@intlify/vue-i18n/base']
+    },
+    {
+      files: ['*.ts'],
+      extends: [
+        'plugin:@typescript-eslint/recommended-requiring-type-checking',
+      ]
+    }
+  ]
```

**Comment by maggie0002** [comment]
> ```diff
> +      files: ['*.ts'],
> +      extends: [
> +        'plugin:@typescript-eslint/recommended-requiring-type-checking',
> +      ]
> ```

Thanks, that seemed to get me half way there. The problem now is that the type-checking is only applied to *.ts files. And in Vue there are single file components where the typescript is at the bottom of a .vue file. So I added *.vue to the overrides for the type-checking, but then it seemed to check everything in the file, it doesn't identify which is vue and which is .ts like it did when it was in the `extends` block, and reports a bunch of errors. Any ideas how to restore type-checking back in the .vue files, while still using the i18n linting?

**Comment by ota-meshi** [comment]
I can't reproduce your problem. Please provide a repository that can reproduce the problem. Or commit the config to the repository.

**Comment by maggie0002** [comment]
> I can't reproduce your problem. Please provide a repository that can reproduce the problem. Or commit the config to the repository.

I have added a type scripting issue to `/src/components/wifi/connect.vue` which is picked up when running lint with my original setup. When I change the setup to the one you mentioned above (which is how the attached is configured) this lint error is picked up anymore. I have included a `eslintrc-original.js` to be able to see the type error get picked up (and will need to remove .json from the package.json to restore the original configuration). 

I guess this isn't very surprising behaviour, because my Typescript is in a .vue file, and .vue is not specified for as a file in the override. But when if you add .vue, then it doesn't identify the <script> blocks, and instead tries to check the whole file: https://eslint.vuejs.org/user-guide/#why-doesn-t-it-work-on-vue-files

[ui.zip](https://github.com/intlify/eslint-plugin-vue-i18n/files/8408086/ui.zip)

**Comment by ota-meshi** [comment]
I don't want to open zip file. Please provide the repository. If not, I will not be able to proceed with this issue.

**Comment by maggie0002** [comment]
> I don't want to open zip file. Please provide the repository. If not, I will not be able to proceed with this issue.

https://github.com/maggie0002/test-repo

I add three files:

.eslintrc.js = The setup you mentioned above, and does not pick up type-checking errors in .vue files
.eslintrc-original.js = the original config which doesn't pick up issues in i18n (the original issue related to this thread)
.eslintrc-includes-vue-files.js = Changed config to `files: ['*.ts', '*.vue'],` to include vue files, but then reports hundreds of errors because `recommended-requiring-type-checking` no longer seems to work correctly on .vue files.

**Comment by ota-meshi** [comment]
You need to add the following overrides section to your configuration.


```diff

  overrides: [
    // ...
+    {
+      files: ['*.vue'],
+      extends: [
+        'plugin:@typescript-eslint/recommended-requiring-type-checking',
+        'plugin:vue/base',
+      ],
+      parserOptions: {
+        parser: require.resolve('@typescript-eslint/parser'),
+      },
+    }
  ],
```

**Comment by maggie0002** [comment]
Fantastic, looks like it is picking up all the lint errors now.

To summarise, for future reference for others:

Remove 'plugin:@typescript-eslint/recommended-requiring-type-checking',`

Add an override block like the following:

```
  overrides: [
    {
      files: ['*.json', '*.json5'],
      extends: ['plugin:@intlify/vue-i18n/base']
    },
    {
      files: ['*.yaml', '*.yml'],
      extends: ['plugin:@intlify/vue-i18n/base']
    },
    {
      files: ['*.ts'],
      extends: ['plugin:@typescript-eslint/recommended-requiring-type-checking']
    },
    {
      files: ['*.vue'],
      extends: [
        'plugin:@typescript-eslint/recommended-requiring-type-checking',
        'plugin:vue/base'
      ],
      parserOptions: {
        parser: require.resolve('@typescript-eslint/parser')
      }
    }
  ],

```

Make sure package.json includes .json files to lint:

`"lint": "eslint --ext .js,.ts,.vue,.json ./",`
