### ISSUE TITLE
Ignore pattern for `no-html-messages` rule

### ISSUE THREAD

**Issue by azamat-sharapov** [intlify/eslint-plugin-vue-i18n#334]
**Please describe what the rule should do:**
`no-html-messages` rule should support ignoring by regex pattern, just like `no-unused-keys` rule.

**Additional context**
I'm using localisation in JavaScript file (not Vue template) and I need HTML in there, like so: `Please click <a href="{link}">here</a> to continue`. Translation are saved in JSON files and it's working fine. However, I get `no-html-messages` warning and I want to ignore it only for this key. There is no way to use `eslint-disable` comment in JSON file and I cannot use `<i18n>` component, because it's JavaScript file, not Vue file.

**Comment by ota-meshi** [comment]
Thank you for posting issue.

You can turn off the `no-html-messages` rule. Any reason why you don't turn off the rule?

**Comment by azamat-sharapov** [comment]
@ota-meshi thanks for your quick reply. We still want to have `no-html-messages` rule, because it's a team project (not solo). However, the case I'm mentioning above is edge case - they is no other way I found to render HTML without causing eslint warning.

**Comment by ota-meshi** [comment]
Why would your team want to use the `no-html-messages` rule? You use HTML in messages. So your team uses HTML in messages. You don't need that rule. You can turn off the `no-html-messages` rule.

**Comment by ota-meshi** [comment]
Also, I think the message you used should ideally be replaced with `<i18n-t>`.

https://vue-i18n.intlify.dev/guide/advanced/component.html

**Comment by azamat-sharapov** [comment]
OK, I think you didn't understand the problem I'm having. Let me show some code, maybe you can help.

**example.js**:
```js
// this is javascript file, not `.vue` file

// using: https://buefy.org/documentation/snackbar/
import { SnackbarProgrammatic as Snackbar } from 'buefy'

// this is dynamic link, we fetch this link from API
const link = 'http://423f23m232.example.com'

// HTML message
const message = `Please click <a href="${link}">here</a>`

Snackbar.open(message)
```

I need to localise this message. How can I do this?  I cannot use `<i18n-t>` component here, it's javascript file. `Vue.compile()` does not work here, because it's webpack build. We _need_ `no-html-messages` rule in team, we _cannot_ disable it. Ideally, we want to be able to ignore `no-html-messages` rule _only for this message_.

**Comment by ota-meshi** [comment]
I recommend using YAML or JSON5 as resource files and suppressing it with comment directives.

**Comment by ota-meshi** [comment]
Also, I think you should request `buefy` to be used safely without XSS attacks.

**Comment by azamat-sharapov** [comment]
Well, it's not small project and we cannot change file format just because this plugin lacks a feature. Our locale files are also used by other tools and external translation services.  
I will consider creating modified version of the rule as a custom eslint rule. Thanks for your help.

**Comment by ota-meshi** [comment]
I don't think this eslint plugin lacks features. I think buefy is lacks some features. Either way I will close this issue.
