### ISSUE TITLE
Incompatibilities with eslint-plugin-unicorn

### ISSUE THREAD

**Issue by ferferga** [intlify/eslint-plugin-vue-i18n#443]
Hello

I posted this issue originally in eslint-plugin-unicorn's repo: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2204

TLDR: There are incompatibilities with some plugins due to how outdated the `@eslint/eslintrc` dependency is in the 2.0.0 version

@kazupon A new release would fix this incompatibility, since the package is already updated in master.
Thank you very much in advance!

**Comment by ota-meshi** [comment]
Thank you for posting the issue!

Does using a pre-released version solve the problem?
https://github.com/intlify/eslint-plugin-vue-i18n/releases/tag/v3.0.0-next.4

**Comment by ferferga** [comment]
Hello @ota-meshi 

My bad for not thinking about checking prereleases! And yes, it fixes the issue for me!

**Comment by ferferga** [comment]
I initially didn't close the issue, as it wasn't fixed in the stable version just yet. However, I figured out you might prefer to keep an smaller backlog regardless if the fixes are shipped in releases or not, so I'm closing this.

@ota-meshi Reopen the issue if you still prefer to keep this open until 3.y.z is released!
