### ISSUE TITLE
Conditional expressions don't use ignore pattern and nodes

### ISSUE THREAD

**Issue by jbayona89** [intlify/eslint-plugin-vue-i18n#51]
Ternary operators do not use ignoreNodes and or Pattern. For example if I have this code:
`<v-icon>{{ item.esPerdido ? 'mdi-thumb-down' : 'mdi-trophy'}}</v-icon>`

and this ignorePattern:

ignorePattern: /^[-#:()&%.,0123456789\s]+|(mdi-.*)$/,

The linting warns me that there are two texts that are wrong.

The problem is that the function `checkVExpressionContainerText` isn't using the ignorePattern rules as `checkRawText`

**Comment by ota-meshi** [comment]
Hi @jbayona89.

Perhaps you need to specify it as a string.
Could you try with the following changes?

```js
{
  ignorePattern: "^[-#:()&%.,0123456789\\s]+|(mdi-.*)$",
}
```

**Comment by ota-meshi** [comment]
Let me know if you still have problems after changing the option.

**Comment by Nettsentrisk** [comment]
The ignoreNodes setting is not applied when doing this:
```vue
 <v-icon>{{
                      !someBoolean
                        ? 'unpublished'
                        : 'published_with_changes'
                    }}
</v-icon>
```
The rule setup: `ignoreNodes: ['v-icon']`

Testet in 2.0.0.
