### ISSUE TITLE
Plans for v3.0.0.

### ISSUE THREAD

**Issue by ota-meshi** [intlify/eslint-plugin-vue-i18n#512]
I would like to list the remaining tasks for v3 release.

- [x] Drop support for older node versions.
- [x] Drop support for older ESLint versions. (I think we can drop support for anything other than the latest version of v8.)
- [x] Update recommended configs.

Do you think there are other tasks?

**Comment by kazupon** [comment]
I think we don't have any other tasks at the moment.

> Drop support for older node versions.

I think we should drop as node v18 and below are no longer supported.

> Drop support for older ESLint versions. (I think we can drop support for anything other than the latest version of v8.)

I agree for dropping support for anything other than the latest version of v8

**Comment by mahula** [comment]
What about supporting eslint versions 9.x?

In our project trying to update the eslint package to the current version v9.3. ,this dependency error occurs:

```
Could not resolve dependency:
npm error peer eslint@"^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0" from @intlify/eslint-plugin-vue-i18n@2.0.0
npm error node_modules/@intlify/eslint-plugin-vue-i18n
npm error   dev @intlify/eslint-plugin-vue-i18n@"^2.0.0" from the root project
```

**Comment by kazupon** [comment]
You can try to install v3.0.0-next.13
https://github.com/intlify/eslint-plugin-vue-i18n/releases/tag/v3.0.0-next.13
