### ISSUE TITLE
Support `@intlify/` v10 

### ISSUE THREAD

**Issue by darthf1** [intlify/eslint-plugin-vue-i18n#566]
Hi,

I would like to try out v9 RC of https://github.com/nuxt-modules/i18n, but unfortunately it means I have to drop this package since it does not support v10 of the  `@intlify/` packages.

Would be great to have support for those, so I can depend on the eslint rules during upgrading.

**Comment by dargmuesli** [comment]
These two PRs are relevant, I think:

- https://github.com/intlify/eslint-plugin-vue-i18n/pull/556
- https://github.com/intlify/eslint-plugin-vue-i18n/pull/557

The latter still needs some work due to the tests failing. I will take a look soon, but if anyone is quicker, go ahead :rocket:

**Comment by maxdzin** [comment]
Strange thing...
I installed the latest `@intlify/eslint-plugin-vue-i18n` v3.2.0, but such an error is still showing:
```
✘ [ERROR] No matching export in "node_modules/.pnpm/@intlify+shared@10.0.5/node_modules/@intlify/shared/dist/shared.mjs" for import "incrementer"

    node_modules/.pnpm/@intlify+core-base@9.14.2/node_modules/@intlify/core-base/dist/core-base.mjs:6:129:
      6 │ ... assign, join, toDisplayString, isArray, incrementer, format as format$1, isPromise, isBoolea...
        ╵                                             ~~~~~~~~~~~


 ERROR  error while updating dependencies:                                                      12:18:49 PM
Error: Build failed with 1 error:
node_modules/.pnpm/@intlify+core-base@9.14.2/node_modules/@intlify/core-base/dist/core-base.mjs:6:129: ERROR: No matching export in "node_modules/.pnpm/@intlify+shared@10.0.5/node_modules/@intlify/shared/dist/shared.mjs" for import "incrementer"
    at failureErrorWithLog (/.../node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1472:15)
    at /.../node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:945:25
    at /.../node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

The `pnpm why @intlify/core-base` shows this:
```
dependencies:
@nuxtjs/i18n 9.1.1
├─┬ @intlify/h3 0.6.1
│ └─┬ @intlify/core 10.0.5
│   └── @intlify/core-base 10.0.5
├─┬ @intlify/unplugin-vue-i18n 6.0.1
│ ├─┬ @intlify/bundle-utils 10.0.0
│ │ └─┬ vue-i18n 10.0.5 peer
│ │   └── @intlify/core-base 10.0.5
│ ├─┬ @intlify/vue-i18n-extensions 7.0.0
│ │ └─┬ vue-i18n 10.0.5 peer
│ │   └── @intlify/core-base 10.0.5
│ └─┬ vue-i18n 10.0.5 peer
│   └── @intlify/core-base 10.0.5
└─┬ vue-i18n 10.0.5
  └── @intlify/core-base 10.0.5

devDependencies:
@intlify/eslint-plugin-vue-i18n 3.2.0
└── @intlify/core-base 9.14.2
```

And, of course, I tried to make a clean install of the dependencies (also removing `pnpm-lock.yaml`), but that is not helped.

So, I'm wondering why `@intlify/eslint-plugin-vue-i18n@3.2.0` used `@intlify/core-base@9.14.2`, instead of v10 (even though v10 being stated in the project dependencies: https://github.com/intlify/eslint-plugin-vue-i18n/blob/4bd9ba029dbad1008759c436bf0143692c7f47e5/package.json#L63)?

@ota-meshi maybe you can suggest something?

**Comment by mkeyy0** [comment]
@maxdzin I guess you have to install the version under the next tag, as it's a breaking change I suppose. https://www.npmjs.com/package/@intlify/eslint-plugin-vue-i18n/v/4.0.0-next.0?activeTab=versions

**Comment by maxdzin** [comment]
@mkeyy0 Thank you 🙏
Indeed, the `next` version works.
