### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by rafaelmaiach** [intlify/eslint-plugin-vue-i18n#69]
Hi, I've installed `"@intlify/eslint-plugin-vue-i18n": "0.4.1"` as described on NPM and uninstalled the older package, but now I get this error on console:

![image](https://user-images.githubusercontent.com/13542718/86501003-92302300-bd6b-11ea-9892-905bea24acfe.png)

Is the documentation outdated?

**Comment by hperchec** [comment]
Hello @rafaelmaiach ! Did you found a solution? Thank you

**Comment by hperchec** [comment]
@rafaelmaiach I'm facing the same issue...

**Comment by hperchec** [comment]
Ok I had a look to this issue. It seems that the new package is scoped (@intlify/...) and it makes configuration errors... [https://eslint.org/docs/user-guide/configuring#use-a-plugin](eslint_documentation)

I have 'fixed' this issue with some changes in .eslintrc.js (i'm using vue-cli):

```javascript
plugins: [
  '@intlify/vue-i18n' // Add this line
],
extends: [
  'plugin:vue/essential',
  '@vue/standard',
  'eslint:recommended'
  // 'plugin:vue-i18n/recommended' // Remove
],
// and adapt plugin name everywhere...
rules: [
  // ...
  '@intlify/vue-i18n/no-html-messages': 'warn',
  '@intlify/vue-i18n/no-missing-keys': 'warn',
  '@intlify/vue-i18n/no-v-html': 'warn',
  // ...
]
```

**Comment by rafaelmaiach** [comment]
Wow, nice! Thank you @hperchec. I'll take a look at this solution.

@kazupon btw, I think the documentation should be updated with these pieces of code to ensure devs use it correctly or, if you or any another contributor can fix this problem so the `vue-i18n` knows that it should get the information from `@intlify/vue-i18n`, would make the configuration simpler.

**Comment by rafaelmaiach** [comment]
Hey @hperchec it worked here. I couldn't find a way to use the `recommended` extension. I think just adding the `@intlify` isn't enough, maybe it needs a change at the library source code.
To make it work I got all the rules from the website and appended the `@intlify` as you said and it seems to be working.

**Comment by hperchec** [comment]
@rafaelmaiach Yes, in @intlify/eslint-plugin-vue-i18n/lib/configs/recommended.js:

```javascript
plugins: ['vue-i18n'], // This declare the plugin 'eslint-plugin-vue-i18n', NOT '@intlify/eslint-plugin-vue-i18n'
```

So eslint crash because it doesn't find 'eslint-plugin-vue-i18n' module...

A strange thing: for `settings` property, it does not require scoped prefix '@intlify/':
```javascript
settings: {
    'vue-i18n': {
      localeDir: './src/i18n/*.json'
    }
  }
```
